server:
  port: 8081
spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/eisetasks
    username: aaaaa
    password: bbbbb
    driver-class-name: org.postgresql.Driver
  profiles:
    active: console-file-logging

jwt:
  issuer: 'agotsulov@gmail.com'
  signingKey: 'talspoc120nxjsapqke1d77'
  aTokenDuration: 30
meta:
  defaultStatus: "inbox"
  defaultOrder: "desc"
  defaultPage: 1
  defaultSize: 25
  minSize: 10
  maxSize: 50

logging:
  path: logs
  file: file.log

app:
  name: eisetasks